services:
  sarif_pong:
    container_name: sarif_pong
    networks:
      - sarifntw
    build: ./
    env_file: ../../.env
    environment:
      - API_KEY
    # ports:
    #   - "1337:1337"
    restart: on-failure
